// ══════════════════════════════════════════════════════════════════════════════
//  Trends & Trade — Library Content Data
//  Edit this file to add / update topic content.
//  Each topic can have a `content` array of blocks:
//    { type:'image',     src:'images/SNRTA001.jpg', alt:'...' }
//    { type:'heading',   text:'...' }
//    { type:'paragraph', text:'...' }
//    { type:'list',      items:['...','...'] }
//    { type:'callout',   text:'...' }
//    { type:'svg',       id:'svg-element-id', caption:'...' }
//  Topics without a `content` array automatically show "Coming Soon".
// ══════════════════════════════════════════════════════════════════════════════

const LIBRARY = [
  // ── STOCKS ─────────────────────────────────────────────────────────────────
  {
    id: 'stocks', icon: '📈', title: 'Stocks',
    desc: 'Stock market basics, PSX, global exchanges, IPOs, dividends, and investing concepts.',
    topics: [
      { id: 'what-is-stock-market',       title: 'What is the Stock Market?',                       level: 'Beginner',     summary: 'An introduction to stock markets, how they work, and why they exist.' },
      { id: 'how-stock-exchanges-work',   title: 'How Stock Exchanges Work',                        level: 'Beginner',     summary: 'Understanding the mechanics of stock exchanges and trading platforms.' },
      { id: 'primary-vs-secondary',       title: 'Primary vs Secondary Market',                     level: 'Beginner',     summary: 'The difference between where stocks are first issued and where they are traded.' },
      { id: 'what-is-ipo',                title: 'What is an IPO?',                                 level: 'Beginner',     summary: 'How companies go public and what an IPO means for investors.' },
      { id: 'shares-equity-ownership',    title: 'Shares, Equity, and Ownership',                   level: 'Beginner',     summary: 'Understanding what owning a share really means.' },
      { id: 'investor-vs-trader',         title: 'Investor vs Trader',                              level: 'Beginner',     summary: 'Key differences in mindset, strategy, and time horizon.' },
      { id: 'fa-beginners-stocks',        title: 'Fundamental Analysis for Beginners',              level: 'Beginner',     summary: 'A starter guide to evaluating stocks using financial data.' },
      { id: 'ta-beginners-stocks',        title: 'Technical Analysis for Beginners',                level: 'Beginner',     summary: 'Using charts and price action to make trading decisions.' },
      { id: 'what-is-eps',                title: 'What is EPS and Why It Matters?',                 level: 'Beginner',     summary: 'Earnings Per Share explained and why investors watch it closely.' },
      { id: 'understanding-pe-ratio',     title: 'Understanding P/E Ratio',                         level: 'Beginner',     summary: 'How to interpret the Price-to-Earnings ratio when evaluating stocks.' },
      { id: 'dividend-yield',             title: 'Dividend Yield Explained',                        level: 'Beginner',     summary: 'What dividends are and how to calculate dividend yield.' },
      { id: 'market-cap',                 title: 'Market Capitalization',                           level: 'Beginner',     summary: 'Small cap, mid cap, and large cap stocks — what the differences mean.' },
      { id: 'financial-statements-intro', title: 'Understanding Financial Statements',              level: 'Intermediate', summary: 'Reading the balance sheet, income statement, and cash flow statement.' },
      { id: 'snr-stocks',                 title: 'Support and Resistance in Stock Trading',         level: 'Intermediate', summary: 'Applying S&R principles to stock chart analysis.' },
      { id: 'risk-management-stocks',     title: 'Risk Management in Stock Market',                 level: 'Intermediate', summary: 'Protecting capital and managing downside in stock trading.' },
    ]
  },

  // ── COMMODITIES ────────────────────────────────────────────────────────────
  {
    id: 'commodities', icon: '🥇', title: 'Commodities',
    desc: 'Gold, silver, oil, supply and demand, inflation, and safe-haven assets.',
    topics: [
      { id: 'what-are-commodities', title: 'What are Commodities?', level: 'Beginner', summary: 'An overview of commodity markets and the assets traded within them.',
        content: [
          { type: 'image', src: 'images/SNRCOM001.jpg', alt: 'What are Commodities' },
          { type: 'paragraph', text: 'Commodities are basic physical goods that are traded in financial markets. These goods are usually raw materials or natural resources used in daily life, business, manufacturing, agriculture, and energy production. Common examples include gold, silver, crude oil, natural gas, wheat, corn, coffee, sugar, and cotton.' },
          { type: 'heading', text: 'Role of Commodity Markets' },
          { type: 'paragraph', text: 'Commodity markets are important because they connect global supply and demand. Producers, businesses, investors, and traders participate in these markets for different reasons. Some use commodities to manage business risk, while others trade them to benefit from price movements.' },
          { type: 'heading', text: 'Categories of Commodities' },
          { type: 'paragraph', text: 'Commodities are generally divided into different categories such as metals, energy, and agricultural products. Metals include gold, silver, copper, and platinum. Energy commodities include crude oil, natural gas, and gasoline. Agricultural commodities include wheat, corn, coffee, sugar, and cotton.' },
          { type: 'heading', text: 'What Moves Commodity Prices' },
          { type: 'paragraph', text: 'Commodity prices can move due to supply shortages, demand changes, geopolitical events, inflation, weather conditions, currency strength, central bank policies, and global economic growth. For example, oil prices may rise during supply disruptions, while gold may attract attention during periods of economic uncertainty.' },
          { type: 'paragraph', text: 'Commodities are widely traded through spot markets, futures contracts, exchange-traded products, and derivatives. However, commodity trading can be highly volatile and requires proper knowledge, discipline, and risk management.' },
          { type: 'callout', text: '<strong>In simple words:</strong> Commodities are raw materials or basic goods that are traded in global markets, such as gold, oil, silver, wheat, and natural gas.' },
          { type: 'callout', text: '<strong>Disclaimer:</strong> This content is provided for general educational and informational purposes only. It does not constitute financial advice or a recommendation to buy, sell, or trade any commodity or financial instrument. Commodity trading involves significant risk due to price volatility, leverage, and global market uncertainty. Past performance does not guarantee future results. Conduct your own research and consult a qualified financial advisor before making any financial decision.' },
        ]
      },
      { id: 'hard-vs-soft', title: 'Hard vs Soft Commodities', level: 'Beginner', summary: 'The difference between mined and grown commodities.',
        content: [
          { type: 'image', src: 'images/SNRCOM002.jpg', alt: 'Hard vs Soft Commodities' },
          { type: 'paragraph', text: 'Commodities are commonly divided into two main categories: hard commodities and soft commodities. Understanding the difference between them helps traders and investors better analyze market behavior, price drivers, and risk factors.' },
          { type: 'heading', text: 'Hard Commodities' },
          { type: 'paragraph', text: 'Hard commodities are natural resources that are mined or extracted from the earth. Examples include gold, silver, copper, crude oil, natural gas, platinum, and other metals or energy products. These commodities are often linked to industrial demand, global growth, mining activity, energy consumption, and geopolitical developments.' },
          { type: 'heading', text: 'Soft Commodities' },
          { type: 'paragraph', text: 'Soft commodities are agricultural products or goods that are grown or produced through farming. Examples include wheat, corn, coffee, sugar, cotton, cocoa, and soybeans. These commodities are strongly affected by weather conditions, crop production, seasonal cycles, supply disruptions, global consumption, and agricultural policies.' },
          { type: 'heading', text: 'Key Differences in Price Drivers' },
          { type: 'paragraph', text: 'Hard commodities often respond to industrial activity, inflation expectations, interest rates, and global economic conditions. Soft commodities can be more sensitive to climate, harvest quality, disease, transportation issues, and seasonal supply. A drought, flood, or unexpected crop shortage can create strong price movement in agricultural markets.' },
          { type: 'paragraph', text: 'Both hard and soft commodities can provide trading opportunities, but they require different types of analysis. A professional trader must understand the unique drivers of each commodity before making decisions.' },
          { type: 'callout', text: '<strong>In simple words:</strong> Hard commodities are mined or extracted, such as gold and oil. Soft commodities are grown, such as wheat, coffee, and cotton.' },
          { type: 'callout', text: '<strong>Disclaimer:</strong> This content is provided for general educational and informational purposes only. It does not constitute financial advice or a recommendation to buy, sell, or trade any commodity or financial instrument. Hard and soft commodities can be highly volatile and may react differently to weather, economic conditions, and geopolitical events. Trading commodities involves risk, including possible loss of capital. Conduct your own research and consult a qualified financial advisor before making any financial decision.' },
        ]
      },
      { id: 'intro-gold-trading', title: 'Introduction to Gold Trading', level: 'Beginner', summary: 'How gold is traded, why it matters, and how to get started.',
        content: [
          { type: 'image', src: 'images/SNRCOM003.jpg', alt: 'Introduction to Gold Trading' },
          { type: 'paragraph', text: 'Gold is one of the most widely followed commodities in the world. It has historically been used as a store of value, a hedge against uncertainty, and an important asset in global financial markets. Gold is traded by investors, institutions, central banks, and short-term traders.' },
          { type: 'heading', text: 'How Gold is Traded' },
          { type: 'paragraph', text: 'Gold trading involves buying or selling gold-related instruments to benefit from price movements. Traders may access gold through spot gold, futures contracts, exchange-traded funds, CFDs, or physical gold, depending on the market and platform available to them.' },
          { type: 'heading', text: 'What Influences Gold Prices' },
          { type: 'paragraph', text: 'Gold prices are influenced by several important factors, including inflation expectations, interest rates, US Dollar strength, central bank policies, geopolitical tensions, global risk sentiment, and demand from investors or jewelry markets. When uncertainty increases, gold may attract demand because many market participants consider it a defensive asset.' },
          { type: 'heading', text: 'Gold and the US Dollar' },
          { type: 'paragraph', text: 'One of the key relationships in gold trading is its connection with the US Dollar and interest rates. Since gold is commonly priced in US Dollars, a stronger Dollar can sometimes put pressure on gold prices, while a weaker Dollar may support gold. Higher interest rates may also reduce gold\'s appeal because gold does not generate interest income.' },
          { type: 'paragraph', text: 'Gold can be attractive for both long-term investors and short-term traders, but it can also be volatile. Sharp price movements may occur during economic data releases, central bank announcements, geopolitical events, or major market shocks. Professional gold trading requires technical analysis, fundamental understanding, and proper risk management.' },
          { type: 'callout', text: '<strong>In simple words:</strong> Gold trading means buying or selling gold-related instruments to benefit from changes in gold prices.' },
          { type: 'callout', text: '<strong>Disclaimer:</strong> This content is provided for general educational and informational purposes only. It does not constitute financial advice or a recommendation to buy, sell, or trade gold or any financial instrument. Gold trading involves risk. Prices can move sharply due to interest rates, inflation, geopolitical events, and market sentiment. Past performance does not guarantee future results. Conduct your own research and consult a qualified financial advisor before making any financial decision.' },
        ]
      },
      { id: 'intro-silver-trading', title: 'Introduction to Silver Trading', level: 'Beginner', summary: 'Silver as an industrial and precious metal — trading the white metal.',
        content: [
          { type: 'image', src: 'images/SNRCOM004.jpg', alt: 'Introduction to Silver Trading' },
          { type: 'paragraph', text: 'Silver is a precious metal that is actively traded in global commodity markets. Like gold, silver is considered a store of value, but it also has strong industrial demand. This combination makes silver unique because its price can be influenced by both investment demand and industrial usage.' },
          { type: 'heading', text: 'Industrial and Investment Demand' },
          { type: 'paragraph', text: 'Silver is used in electronics, solar panels, medical equipment, batteries, jewelry, and various industrial applications. Because of this, silver prices may react not only to inflation and market uncertainty but also to industrial growth, manufacturing demand, and technological trends.' },
          { type: 'heading', text: 'How Silver is Traded' },
          { type: 'paragraph', text: 'Traders can access silver through spot silver, futures contracts, exchange-traded products, CFDs, or physical silver. Short-term traders often focus on price action, chart patterns, support and resistance, and market volatility. Long-term investors may study industrial demand, supply conditions, inflation trends, and monetary policy.' },
          { type: 'heading', text: 'Silver Volatility and Risk' },
          { type: 'paragraph', text: 'Silver is often more volatile than gold. This means it can move faster and with larger percentage changes. While this may create trading opportunities, it also increases risk. Traders must be careful with position sizing, leverage, and stop-loss placement.' },
          { type: 'paragraph', text: 'Silver may also be influenced by the US Dollar, interest rates, mining supply, global economic growth, and investor sentiment. During periods of uncertainty, silver may attract safe-haven demand, but during economic expansion, it may also benefit from industrial demand.' },
          { type: 'callout', text: '<strong>In simple words:</strong> Silver trading means buying or selling silver-related instruments to benefit from price movements in the silver market.' },
          { type: 'callout', text: '<strong>Disclaimer:</strong> This content is provided for general educational and informational purposes only. It does not constitute financial advice or a recommendation to buy, sell, or trade silver or any financial instrument. Silver prices can be highly volatile and may react to industrial demand, inflation, interest rates, and market sentiment. Conduct your own research and consult a qualified financial advisor before making any financial decision.' },
        ]
      },
      { id: 'intro-oil-trading', title: 'Introduction to Crude Oil Trading', level: 'Beginner', summary: 'How crude oil markets work and what drives price movements.',
        content: [
          { type: 'image', src: 'images/SNRCOM005.jpg', alt: 'Introduction to Crude Oil Trading' },
          { type: 'paragraph', text: 'Crude oil is one of the most important energy commodities in the world. It plays a major role in transportation, manufacturing, power generation, and global economic activity. Because of its importance, crude oil is actively traded by institutions, producers, investors, and short-term traders.' },
          { type: 'heading', text: 'How Crude Oil is Traded' },
          { type: 'paragraph', text: 'Crude oil trading involves buying or selling oil-related instruments to benefit from price movements. Common oil benchmarks include WTI crude oil and Brent crude oil. WTI is commonly associated with the US market, while Brent is widely used as a global oil pricing benchmark.' },
          { type: 'heading', text: 'What Moves Oil Prices' },
          { type: 'paragraph', text: 'Oil prices are strongly affected by supply and demand. When global demand rises or supply becomes restricted, oil prices may increase. When supply is high or demand weakens, oil prices may decline. Factors such as OPEC+ production decisions, geopolitical tensions, inventory reports, economic growth, transportation demand, and currency movements can all influence oil prices.' },
          { type: 'heading', text: 'Volatility and Risk' },
          { type: 'paragraph', text: 'Crude oil is known for sharp price movements, especially during major news events. Reports such as weekly inventory data, production announcements, conflicts in oil-producing regions, and global economic updates can create strong volatility.' },
          { type: 'paragraph', text: 'Oil trading can be suitable for experienced traders who understand commodity cycles, technical analysis, news impact, and risk management. However, it can be risky for beginners due to fast price movement, leverage, spreads, and sudden market reactions.' },
          { type: 'callout', text: '<strong>In simple words:</strong> Crude oil trading means buying or selling oil-related instruments to benefit from changes in oil prices.' },
          { type: 'callout', text: '<strong>Disclaimer:</strong> This content is provided for general educational and informational purposes only. It does not constitute financial advice or a recommendation to buy, sell, or trade crude oil or any financial instrument. Oil prices can move sharply due to supply disruptions, OPEC+ decisions, geopolitical events, and economic conditions. Conduct your own research and consult a qualified financial advisor before making any financial decision.' },
        ]
      },
      { id: 'factors-gold-prices', title: 'Factors Affecting Gold Prices', level: 'Intermediate', summary: 'The key drivers behind gold price movements.',
        content: [
          { type: 'image', src: 'images/SNRCOM006.jpg', alt: 'Factors Affecting Gold Prices' },
          { type: 'paragraph', text: 'Gold prices are influenced by a wide range of economic, financial, and geopolitical factors. Understanding these factors helps traders and investors analyze why gold moves and what may affect future price direction.' },
          { type: 'heading', text: 'Interest Rates' },
          { type: 'paragraph', text: 'One of the most important factors affecting gold is interest rates. When interest rates rise, gold may become less attractive because it does not generate interest income. When interest rates fall or are expected to fall, gold may become more attractive for investors.' },
          { type: 'heading', text: 'Inflation' },
          { type: 'paragraph', text: 'Gold is often viewed as a hedge against inflation because it may preserve value when the purchasing power of currency declines. During periods of high inflation or inflation uncertainty, demand for gold may increase.' },
          { type: 'heading', text: 'US Dollar Strength' },
          { type: 'paragraph', text: 'Since gold is commonly priced in US Dollars, a stronger Dollar can make gold more expensive for buyers using other currencies, which may put pressure on prices. A weaker Dollar may support gold demand.' },
          { type: 'heading', text: 'Geopolitics and Safe-Haven Demand' },
          { type: 'paragraph', text: 'Geopolitical tension, financial market stress, banking concerns, and economic uncertainty can also increase demand for gold as a safe-haven asset. In uncertain times, investors may move toward gold to reduce exposure to riskier assets.' },
          { type: 'heading', text: 'Central Banks and Supply' },
          { type: 'paragraph', text: 'Central bank activity is another key factor. When central banks buy gold, it can support long-term demand. On the supply side, mining production, refining, and physical demand from jewelry and investment markets may also influence prices.' },
          { type: 'paragraph', text: 'Gold price movement is rarely caused by one factor alone. Professional traders analyze the combined impact of interest rates, inflation, the US Dollar, global risk sentiment, and technical price structure.' },
          { type: 'callout', text: '<strong>In simple words:</strong> Gold prices are affected by interest rates, inflation, the US Dollar, central banks, global uncertainty, and supply and demand.' },
          { type: 'callout', text: '<strong>Disclaimer:</strong> This content is provided for general educational and informational purposes only. It does not constitute financial advice or a recommendation to buy, sell, or trade gold or any financial instrument. No factor or analysis can guarantee future gold price movement. Gold can be volatile and may react unexpectedly to news and market conditions. Conduct your own research and consult a qualified financial advisor before making any financial decision.' },
        ]
      },
      { id: 'factors-oil-prices', title: 'Factors Affecting Oil Prices', level: 'Intermediate', summary: 'Supply, demand, geopolitics, and OPEC\'s role in oil pricing.',
        content: [
          { type: 'image', src: 'images/SNRCOM007.jpg', alt: 'Factors Affecting Oil Prices' },
          { type: 'paragraph', text: 'Oil prices are mainly driven by supply and demand, but many global factors can influence the balance between them. Because crude oil is essential for transportation, industry, and energy production, its price is closely connected to the global economy.' },
          { type: 'heading', text: 'Supply-Side Factors' },
          { type: 'paragraph', text: 'On the supply side, oil prices can be affected by production levels, OPEC+ decisions, drilling activity, sanctions, conflicts, natural disasters, and transportation disruptions. If supply becomes limited while demand remains strong, oil prices may rise. If supply increases or production exceeds demand, prices may fall.' },
          { type: 'heading', text: 'Demand-Side Factors' },
          { type: 'paragraph', text: 'On the demand side, global economic growth is a major factor. When economies are expanding, demand for transportation, manufacturing, and energy usually increases. This can support oil prices. During economic slowdowns or recessions, demand may weaken and put pressure on prices.' },
          { type: 'heading', text: 'Inventory Reports' },
          { type: 'paragraph', text: 'Inventory reports are also important. If crude oil inventories rise more than expected, it may indicate weaker demand or excess supply. If inventories fall, it may suggest stronger demand or tighter supply conditions.' },
          { type: 'heading', text: 'Other Influences' },
          { type: 'paragraph', text: 'Geopolitical events can create sudden volatility in oil markets, especially when they involve major oil-producing regions or shipping routes. Currency movements also matter because crude oil is commonly priced in US Dollars. Seasonal demand such as travel seasons, heating demand, and industrial cycles may also influence consumption patterns.' },
          { type: 'paragraph', text: 'Professional oil traders study supply reports, demand forecasts, inventory data, geopolitical risks, economic indicators, and technical chart structure before making trading decisions.' },
          { type: 'callout', text: '<strong>In simple words:</strong> Oil prices are affected by supply, demand, OPEC+ decisions, inventories, economic growth, geopolitical events, and currency movements.' },
          { type: 'callout', text: '<strong>Disclaimer:</strong> This content is provided for general educational and informational purposes only. It does not constitute financial advice or a recommendation to buy, sell, or trade crude oil or any financial instrument. Oil markets can be highly volatile and unpredictable. No analysis can guarantee any specific trading outcome. Conduct your own research and consult a qualified financial advisor before making any financial decision.' },
        ]
      },
      { id: 'commodity-cycles', title: 'Commodity Market Cycles', level: 'Intermediate', summary: 'Understanding the cyclical nature of commodity markets.',
        content: [
          { type: 'image', src: 'images/SNRCOM008.jpg', alt: 'Commodity Market Cycles' },
          { type: 'paragraph', text: 'Commodity markets often move in cycles. These cycles are driven by changes in supply, demand, production capacity, economic growth, inflation, and investor sentiment. Understanding commodity market cycles helps traders and investors identify broader market conditions and avoid emotional decision-making.' },
          { type: 'heading', text: 'How a Commodity Cycle Works' },
          { type: 'paragraph', text: 'A commodity cycle usually includes periods of rising prices, peak demand, oversupply, falling prices, and recovery. When demand is strong and supply is limited, commodity prices may rise. Higher prices can encourage producers to increase production. Over time, increased production may create excess supply, which can push prices lower.' },
          { type: 'paragraph', text: 'When prices fall too much, producers may reduce output, delay projects, or cut investment. This can eventually reduce supply and create conditions for prices to recover. This repeating process is one reason commodity markets often move in long-term cycles.' },
          { type: 'heading', text: 'Cycle Lengths Vary by Commodity' },
          { type: 'paragraph', text: 'Different commodities may have different cycle lengths. Agricultural commodities can be affected by seasonal cycles and weather patterns, while metals and energy commodities may follow longer investment and production cycles. For example, mining projects and oil production investments can take years to develop.' },
          { type: 'heading', text: 'Macroeconomic Influence' },
          { type: 'paragraph', text: 'Commodity cycles are also influenced by macroeconomic conditions. Inflation, interest rates, currency strength, global growth, industrial demand, and geopolitical events can all accelerate or slow down a cycle. Traders use commodity cycle analysis to understand the bigger picture, but cycles are not perfect and do not always repeat exactly.' },
          { type: 'callout', text: '<strong>In simple words:</strong> Commodity market cycles are repeated phases of rising and falling prices caused by changes in supply, demand, production, and economic conditions.' },
          { type: 'callout', text: '<strong>Disclaimer:</strong> This content is provided for general educational and informational purposes only. It does not constitute financial advice or a recommendation to buy, sell, or trade any commodity or financial instrument. Commodity cycles can be difficult to predict and may change due to unexpected events. Historical cycles do not guarantee future price behavior. Conduct your own research and consult a qualified financial advisor before making any financial decision.' },
        ]
      },
      { id: 'inflation-commodities', title: 'Inflation and Its Impact on Commodities', level: 'Intermediate', summary: 'Why commodities often rise during inflationary periods.',
        content: [
          { type: 'image', src: 'images/SNRCOM009.jpg', alt: 'Inflation and Its Impact on Commodities' },
          { type: 'paragraph', text: 'Inflation is the general rise in prices of goods and services over time. It reduces the purchasing power of money and can have a major impact on commodity markets. Since commodities are physical goods used in the real economy, they are often closely connected to inflation trends.' },
          { type: 'heading', text: 'How Inflation Affects Commodities' },
          { type: 'paragraph', text: 'When inflation rises, commodity prices may also increase because raw materials, energy, transportation, labor, and production costs become more expensive. For example, higher crude oil prices can increase transportation and manufacturing costs, which may contribute to broader inflation.' },
          { type: 'heading', text: 'Gold and Inflation' },
          { type: 'paragraph', text: 'Some commodities, especially gold, are often viewed as inflation-sensitive assets. During inflationary periods, investors may look toward gold or other real assets to protect purchasing power. However, gold does not always rise during inflation because interest rates, the US Dollar, and central bank policy also play an important role.' },
          { type: 'heading', text: 'Energy and Agricultural Commodities' },
          { type: 'paragraph', text: 'Energy commodities such as oil and natural gas can both influence and respond to inflation. Rising energy prices can increase inflation, while high inflation can affect consumer demand and economic activity. Agricultural commodities may also be affected by inflation through higher fertilizer, fuel, labor, and transportation costs.' },
          { type: 'heading', text: 'Inflation and Central Bank Decisions' },
          { type: 'paragraph', text: 'For traders, inflation data is important because it can influence central bank decisions. If inflation is high, central banks may raise interest rates, which can affect currencies, gold, oil, and other commodities.' },
          { type: 'callout', text: '<strong>In simple words:</strong> Inflation can increase commodity prices because raw materials, energy, and production costs become more expensive. It can also change investor demand for assets like gold.' },
          { type: 'callout', text: '<strong>Disclaimer:</strong> This content is provided for general educational and informational purposes only. It does not constitute financial advice or a recommendation to buy, sell, or trade any commodity or financial instrument. Inflation and commodity prices are influenced by many factors including central bank policy, interest rates, and supply conditions. No inflation-based analysis can guarantee future market direction. Conduct your own research and consult a qualified financial advisor before making any financial decision.' },
        ]
      },
      { id: 'safe-haven-assets', title: 'Safe Haven Assets Explained', level: 'Beginner', summary: 'Assets that hold value during market uncertainty.',
        content: [
          { type: 'image', src: 'images/SNRCOM010.jpg', alt: 'Safe Haven Assets Explained' },
          { type: 'paragraph', text: 'Safe haven assets are assets that investors often consider during periods of uncertainty, market stress, economic weakness, geopolitical tension, or financial instability. These assets are called "safe haven" because they may help preserve value when riskier markets are under pressure.' },
          { type: 'heading', text: 'Gold as a Safe Haven' },
          { type: 'paragraph', text: 'Gold is one of the most well-known safe haven assets. Many investors turn to gold during uncertain times because it has a long history as a store of value. It is not directly tied to the performance of a single company or government, which makes it attractive during periods of financial concern.' },
          { type: 'heading', text: 'Other Safe Haven Assets' },
          { type: 'paragraph', text: 'Other assets sometimes considered safe havens include certain government bonds, the US Dollar, Swiss Franc, Japanese Yen, and cash equivalents. However, safe haven behavior can change depending on the market environment.' },
          { type: 'heading', text: 'Safe Haven Does Not Mean Risk-Free' },
          { type: 'paragraph', text: 'It is important to understand that "safe haven" does not mean risk-free. Even safe haven assets can decline in value. For example, gold may fall if interest rates rise sharply or if the US Dollar strengthens. Government bonds may lose value when interest rates increase.' },
          { type: 'heading', text: 'When Safe Haven Demand Increases' },
          { type: 'paragraph', text: 'Safe haven demand usually increases when investors become defensive. This may happen during stock market declines, banking concerns, wars, recessions, inflation uncertainty, or global financial stress. Professional traders do not buy safe haven assets blindly. They analyze the reason behind the market uncertainty, interest rates, currency movement, and technical price structure before making decisions.' },
          { type: 'callout', text: '<strong>In simple words:</strong> Safe haven assets are assets that investors may prefer during uncertain or risky market conditions, but they are not completely risk-free.' },
          { type: 'callout', text: '<strong>Disclaimer:</strong> This content is provided for general educational and informational purposes only. It does not constitute financial advice or a recommendation to buy, sell, or trade any asset or financial instrument. Safe haven assets are not guaranteed to protect capital and may decline in value. The term "safe haven" should not be understood as "risk-free." Conduct your own research and consult a qualified financial advisor before making any financial decision.' },
        ]
      },
      { id: 'supply-demand-commodities', title: 'Supply and Demand in Commodity Markets', level: 'Beginner', summary: 'How supply and demand fundamentals drive commodity prices.',
        content: [
          { type: 'image', src: 'images/SNRCOM011.jpg', alt: 'Supply and Demand in Commodity Markets' },
          { type: 'paragraph', text: 'Supply and demand are the foundation of commodity price movement. Commodity prices rise and fall based on the balance between how much of a commodity is available and how much buyers need or want.' },
          { type: 'heading', text: 'Supply' },
          { type: 'paragraph', text: 'Supply refers to the amount of a commodity available in the market. It can be affected by production levels, mining output, farming conditions, inventories, transportation, weather, geopolitical events, and government policies. If supply decreases while demand remains strong, prices may rise.' },
          { type: 'heading', text: 'Demand' },
          { type: 'paragraph', text: 'Demand refers to how much of a commodity buyers are willing to purchase. Demand can be influenced by economic growth, industrial activity, consumer behavior, seasonal needs, technology, and global trade. If demand increases while supply is limited, prices may move higher.' },
          { type: 'heading', text: 'Real-World Examples' },
          { type: 'paragraph', text: 'For example, crude oil prices may rise if demand increases while production is restricted. Gold prices may rise if investors increase demand during uncertain times. Agricultural prices may rise if bad weather reduces crop supply.' },
          { type: 'heading', text: 'Markets Price in Expectations' },
          { type: 'paragraph', text: 'Supply and demand analysis is important because commodities are directly connected to the real economy. However, price movement is not always simple. Markets often react to expectations before actual supply or demand changes occur. Traders may price in future shortages, future demand growth, or expected policy changes.' },
          { type: 'paragraph', text: 'Professional traders combine supply and demand analysis with technical analysis, market sentiment, inventory data, and macroeconomic conditions.' },
          { type: 'callout', text: '<strong>In simple words:</strong> Commodity prices usually rise when demand is strong and supply is limited. Prices usually fall when supply is high and demand is weak.' },
          { type: 'callout', text: '<strong>Disclaimer:</strong> This content is provided for general educational and informational purposes only. It does not constitute financial advice or a recommendation to buy, sell, or trade any commodity or financial instrument. Supply and demand conditions can change quickly due to economic events, weather, and geopolitical developments. Analysis does not guarantee future price movement. Conduct your own research and consult a qualified financial advisor before making any financial decision.' },
        ]
      },
      { id: 'commodity-futures', title: 'Commodity Futures Explained', level: 'Intermediate', summary: 'What futures contracts are and how they work in commodity markets.',
        content: [
          { type: 'image', src: 'images/SNRCOM012.jpg', alt: 'Commodity Futures Explained' },
          { type: 'paragraph', text: 'Commodity futures are financial contracts that allow traders and investors to buy or sell a commodity at a predetermined price for delivery or settlement at a future date. Futures contracts are commonly used in markets such as crude oil, gold, silver, natural gas, wheat, corn, and other commodities.' },
          { type: 'heading', text: 'How Futures Contracts Work' },
          { type: 'paragraph', text: 'A futures contract specifies the commodity, quantity, quality, delivery month, and contract terms. In practice, many traders do not take physical delivery of the commodity. Instead, they trade the price movement of the futures contract before expiry.' },
          { type: 'heading', text: 'Hedgers and Speculators' },
          { type: 'paragraph', text: 'Commodity futures are used by two main types of participants: hedgers and speculators. Hedgers use futures to manage price risk. For example, an airline may use oil futures to protect against rising fuel prices. A farmer may use agricultural futures to manage the risk of falling crop prices. Speculators trade futures to benefit from price movement without wanting the physical commodity.' },
          { type: 'heading', text: 'Expiration and Complexity' },
          { type: 'paragraph', text: 'One important feature of futures is expiration. Each contract has a specific expiry date, and traders must understand contract rollover, settlement rules, margin requirements, and price differences between contract months.' },
          { type: 'paragraph', text: 'Commodity futures can be powerful tools, but they are more complex than simple spot trading. Professional traders must understand contract specifications, margin, volatility, liquidity, and risk before participating.' },
          { type: 'callout', text: '<strong>In simple words:</strong> Commodity futures are contracts to buy or sell a commodity at a set price for a future date. They are used for hedging, speculation, and price risk management.' },
          { type: 'callout', text: '<strong>Disclaimer:</strong> This content is provided for general educational and informational purposes only. It does not constitute financial advice or a recommendation to buy, sell, or trade commodity futures or any financial instrument. Futures trading involves substantial risk, including leverage, margin requirements, expiry, and rapid price movement. Losses can be significant. Conduct your own research and consult a qualified financial advisor before making any financial decision.' },
        ]
      },
      { id: 'spot-vs-futures-commodity', title: 'Spot vs Futures Commodity Trading', level: 'Intermediate', summary: 'The difference between spot price and futures contracts.',
        content: [
          { type: 'image', src: 'images/SNRCOM013.jpg', alt: 'Spot vs Futures Commodity Trading' },
          { type: 'paragraph', text: 'Spot and futures trading are two common ways to participate in commodity markets. Both involve commodity prices, but they work differently and serve different purposes.' },
          { type: 'heading', text: 'Spot Trading' },
          { type: 'paragraph', text: 'Spot commodity trading refers to buying or selling a commodity at the current market price, also known as the spot price. Settlement usually happens immediately or within a short period, depending on the market. Spot trading reflects the current value of the commodity.' },
          { type: 'heading', text: 'Futures Trading' },
          { type: 'paragraph', text: 'Futures commodity trading involves contracts to buy or sell a commodity at a predetermined price for a future date. Futures prices may be different from spot prices because they include expectations about future supply, demand, storage costs, interest rates, and market conditions.' },
          { type: 'heading', text: 'Key Differences' },
          { type: 'paragraph', text: 'Spot trading is often simpler to understand because it focuses on the current price. Futures trading is more complex because traders must consider expiry dates, contract rollover, margin requirements, and settlement rules.' },
          { type: 'paragraph', text: 'For example, spot gold shows the current market price of gold, while gold futures reflect the price of a contract for a specific future month. Similarly, spot oil and oil futures may show different prices depending on market expectations and contract timing.' },
          { type: 'heading', text: 'Which to Choose' },
          { type: 'paragraph', text: 'Futures markets are commonly used by producers, companies, and institutions to manage price risk. Spot markets may be preferred by participants who want exposure to current pricing without dealing with contract expiry. Both carry risk. The right choice depends on the trader\'s objective, experience, capital, and understanding of market structure.' },
          { type: 'callout', text: '<strong>In simple words:</strong> Spot trading is based on the current market price, while futures trading is based on a contract price for a future date.' },
          { type: 'callout', text: '<strong>Disclaimer:</strong> This content is provided for general educational and informational purposes only. It does not constitute financial advice or a recommendation to buy, sell, or trade spot commodities, futures, or any financial instrument. Both spot and futures trading involve risk. Prices may move rapidly and losses can be significant. Conduct your own research and consult a qualified financial advisor before making any financial decision.' },
        ]
      },
    ]
  },

  // ── CRYPTO ─────────────────────────────────────────────────────────────────
  {
    id: 'crypto', icon: '₿', title: 'Crypto',
    desc: 'Bitcoin, Ethereum, blockchain, wallets, exchanges, leverage, liquidation, and crypto risk.',
    topics: [
      { id: 'what-is-crypto',             title: 'What is Cryptocurrency?',                        level: 'Beginner',     summary: 'A beginner-friendly introduction to digital currencies.' },
      { id: 'bitcoin-explained',          title: 'Bitcoin Explained for Beginners',                level: 'Beginner',     summary: 'The origin, purpose, and mechanics of Bitcoin.' },
      { id: 'ethereum-smart-contracts',   title: 'Ethereum and Smart Contracts',                   level: 'Beginner',     summary: 'How Ethereum works and what smart contracts enable.' },
      { id: 'coins-vs-tokens',            title: 'Coins vs Tokens',                                level: 'Beginner',     summary: 'The difference between native coins and project tokens.' },
      { id: 'what-is-blockchain',         title: 'What is Blockchain?',                            level: 'Beginner',     summary: 'The technology underpinning all cryptocurrencies.' },
      { id: 'cex-vs-dex',                 title: 'Centralized vs Decentralized Exchanges',         level: 'Beginner',     summary: 'Understanding CEX and DEX trading platforms.' },
      { id: 'spot-vs-futures-crypto',     title: 'Spot vs Futures Trading in Crypto',              level: 'Intermediate', summary: 'Key differences and which suits your risk profile.' },
      { id: 'leverage-crypto',            title: 'Leverage in Crypto Trading',                     level: 'Intermediate', summary: 'How leverage amplifies both gains and losses in crypto.' },
      { id: 'liquidation-crypto',         title: 'Liquidation in Crypto Futures',                  level: 'Intermediate', summary: 'What liquidation means and how to avoid it.' },
      { id: 'crypto-wallets',             title: 'Crypto Wallets: Hot vs Cold',                    level: 'Beginner',     summary: 'Keeping your crypto safe — online vs offline storage.' },
      { id: 'stablecoins',                title: 'Stablecoins: USDT, USDC and Their Role',         level: 'Beginner',     summary: 'How stablecoins work and why traders use them.' },
      { id: 'market-sentiment-crypto',    title: 'Market Sentiment in Crypto',                     level: 'Intermediate', summary: 'How crowd psychology drives crypto price cycles.' },
      { id: 'fear-greed-index',           title: 'Fear and Greed Index Explained',                 level: 'Beginner',     summary: 'Using sentiment indicators to time market entries.' },
      { id: 'crypto-risk-management',     title: 'Crypto Risk Management for Beginners',           level: 'Beginner',     summary: 'Protecting your capital in the volatile crypto market.' },
    ]
  },

  // ── FOREX ──────────────────────────────────────────────────────────────────
  {
    id: 'forex', icon: '💱', title: 'Forex',
    desc: 'Currency pairs, pips, spread, lot size, margin, leverage, and economic calendar.',
    topics: [
      { id: 'what-is-forex', title: 'What is Forex Trading?', level: 'Beginner', summary: 'An introduction to the world\'s largest financial market.',
        content: [
          { type: 'image', src: 'images/SNRFX001.jpg', alt: 'What is Forex Trading' },
          { type: 'paragraph', text: 'Forex trading, also known as foreign exchange trading or currency trading, is the process of buying one currency and selling another currency at the same time. The forex market is the largest and most actively traded financial market in the world, where currencies such as the US Dollar, Euro, British Pound, Japanese Yen, Swiss Franc, and other global currencies are exchanged.' },
          { type: 'heading', text: 'How Forex Trading Works' },
          { type: 'paragraph', text: 'The main purpose of forex trading is to benefit from changes in currency prices. Currency values move due to many factors, including interest rates, inflation, economic data, central bank decisions, political events, global trade, and market sentiment. For example, if a trader believes the Euro will strengthen against the US Dollar, they may buy EUR/USD. If the Euro rises against the Dollar, the trader may make a profit. If the price moves against the trade, the trader may face a loss.' },
          { type: 'heading', text: 'Currency Pairs' },
          { type: 'paragraph', text: 'Forex is traded in currency pairs. This means one currency is compared against another. Some common examples include EUR/USD, GBP/USD, USD/JPY, and USD/CHF. The first currency in the pair is called the base currency, while the second currency is called the quote currency.' },
          { type: 'heading', text: 'Why Forex is Popular' },
          { type: 'paragraph', text: 'Forex trading is popular because the market is highly liquid, available almost 24 hours a day during weekdays, and provides opportunities in both rising and falling markets. However, it is also a highly risky market, especially when leverage is used. Small price movements can create significant gains or losses.' },
          { type: 'heading', text: 'What Forex Trading Requires' },
          { type: 'paragraph', text: 'Successful forex trading requires knowledge, discipline, risk management, and a clear understanding of market behavior. Traders should not treat forex as a quick-money opportunity. Instead, it should be approached as a professional financial skill that requires continuous learning, patience, and proper strategy.' },
          { type: 'callout', text: '<strong>In simple words:</strong> Forex trading is the buying and selling of currencies with the aim of benefiting from changes in exchange rates.' },
          { type: 'callout', text: '<strong>Disclaimer:</strong> This content is provided for general educational and informational purposes only. It does not constitute financial advice or a recommendation to buy, sell, or trade any currency or financial instrument. Forex trading involves significant risk. The use of leverage can magnify both profits and losses, and traders may lose part or all of their invested capital. Past performance does not guarantee future results. Conduct your own research and consult a qualified financial advisor before making any financial decision.' },
        ]
      },
      { id: 'currency-pairs', title: 'Major, Minor, and Exotic Pairs', level: 'Beginner', summary: 'Understanding the different categories of currency pairs.',
        content: [
          { type: 'image', src: 'images/SNRFX002.jpg', alt: 'Major Minor and Exotic Pairs' },
          { type: 'paragraph', text: 'In forex trading, currencies are traded in pairs. These currency pairs are generally divided into three main categories: major pairs, minor pairs, and exotic pairs. Understanding these categories helps traders identify market liquidity, volatility, trading cost, and overall risk level.' },
          { type: 'heading', text: 'Major Currency Pairs' },
          { type: 'paragraph', text: 'Major currency pairs include the most actively traded currencies in the world and always involve the US Dollar. Examples include EUR/USD, GBP/USD, USD/JPY, USD/CHF, AUD/USD, USD/CAD, and NZD/USD. These pairs usually have high liquidity, tighter spreads, and more stable price movement. Because of this, major pairs are commonly preferred by beginner and professional traders.' },
          { type: 'heading', text: 'Minor Currency Pairs' },
          { type: 'paragraph', text: 'Minor currency pairs, also known as cross currency pairs, do not include the US Dollar but involve major global currencies. Examples include EUR/GBP, EUR/JPY, GBP/JPY, AUD/JPY, and EUR/AUD. These pairs can offer strong trading opportunities, but they may have wider spreads and more volatility than major pairs.' },
          { type: 'heading', text: 'Exotic Currency Pairs' },
          { type: 'paragraph', text: 'Exotic currency pairs include one major currency and one currency from an emerging or smaller economy. Examples may include USD/TRY, USD/ZAR, USD/MXN, EUR/TRY, and USD/SGD. Exotic pairs usually have lower liquidity, wider spreads, and higher volatility. They can move sharply due to political events, economic instability, inflation, or lower market participation.' },
          { type: 'heading', text: 'Choosing the Right Pair' },
          { type: 'paragraph', text: 'The choice between major, minor, and exotic pairs depends on the trader\'s experience, strategy, risk tolerance, and market understanding. Major pairs are generally more suitable for learning and structured trading, while exotic pairs require more caution due to unpredictable price behavior and higher transaction costs. Professional traders study volatility, spread, session timing, economic news, and technical structure before entering a trade.' },
          { type: 'callout', text: '<strong>In simple words:</strong> Major pairs are the most liquid and popular, minor pairs exclude the US Dollar, and exotic pairs involve emerging market currencies with higher risk and volatility.' },
          { type: 'callout', text: '<strong>Disclaimer:</strong> This content is provided for general educational and informational purposes only. It does not constitute financial advice or a recommendation to buy, sell, or trade any currency or financial instrument. Currency pairs can behave differently based on liquidity, volatility, and economic conditions. The use of leverage can magnify both profits and losses. Conduct your own research and consult a qualified financial advisor before making any financial decision.' },
        ]
      },
      { id: 'base-quote-currency', title: 'Base Currency and Quote Currency', level: 'Beginner', summary: 'How currency pair pricing works.',
        content: [
          { type: 'image', src: 'images/SNRFX003.jpg', alt: 'Base Currency and Quote Currency' },
          { type: 'paragraph', text: 'In forex trading, every currency pair consists of two currencies: the base currency and the quote currency. Understanding this concept is essential because it explains how currency prices are read and how profit or loss is calculated.' },
          { type: 'heading', text: 'Base and Quote Explained' },
          { type: 'paragraph', text: 'The base currency is the first currency shown in a currency pair. The quote currency is the second currency shown in the pair. For example, in EUR/USD, EUR is the base currency and USD is the quote currency. If EUR/USD is trading at 1.1000, it means 1 Euro is equal to 1.1000 US Dollars.' },
          { type: 'heading', text: 'Reading the Price' },
          { type: 'paragraph', text: 'The price of a forex pair shows how much of the quote currency is needed to buy one unit of the base currency. When the price of EUR/USD rises, it means the Euro is becoming stronger against the US Dollar. When the price falls, it means the Euro is weakening against the US Dollar.' },
          { type: 'heading', text: 'Buying and Selling' },
          { type: 'paragraph', text: 'If a trader buys a currency pair, they are buying the base currency and selling the quote currency. If a trader sells a currency pair, they are selling the base currency and buying the quote currency. This is why forex trading always involves two currencies at the same time.' },
          { type: 'paragraph', text: 'For example, if a trader buys GBP/USD, they expect the British Pound to strengthen against the US Dollar. If the price moves upward, the trade may become profitable. If the price moves downward, the trade may result in a loss.' },
          { type: 'callout', text: '<strong>In simple words:</strong> The base currency is the first currency in a pair, and the quote currency is the second. The price tells how much of the quote currency is needed to buy one unit of the base currency.' },
          { type: 'callout', text: '<strong>Disclaimer:</strong> This content is provided for general educational and informational purposes only. It does not constitute financial advice or a recommendation to buy, sell, or trade any currency or financial instrument. Exchange rates can move quickly due to economic data, interest rates, and geopolitical events. The use of leverage can magnify both profits and losses. Conduct your own research and consult a qualified financial advisor before making any financial decision.' },
        ]
      },
      { id: 'what-are-pips', title: 'What are Pips in Forex?', level: 'Beginner', summary: 'Understanding pip values and how to calculate them.',
        content: [
          { type: 'image', src: 'images/SNRFX004.jpg', alt: 'What are Pips in Forex' },
          { type: 'paragraph', text: 'A pip is one of the most important measurement units in forex trading. It is used to measure the movement in the price of a currency pair. The word "pip" commonly refers to "percentage in point" or "price interest point."' },
          { type: 'heading', text: 'How Pips are Measured' },
          { type: 'paragraph', text: 'In most currency pairs, one pip is equal to the fourth decimal place. For example, if EUR/USD moves from 1.1000 to 1.1001, this movement is equal to 1 pip. If the price moves from 1.1000 to 1.1050, the movement is 50 pips.' },
          { type: 'paragraph', text: 'For Japanese Yen pairs, such as USD/JPY or EUR/JPY, one pip is usually measured at the second decimal place. For example, if USD/JPY moves from 150.00 to 150.01, that movement is equal to 1 pip.' },
          { type: 'heading', text: 'Why Pips Matter' },
          { type: 'paragraph', text: 'Pips help traders calculate profit, loss, risk, and reward. Instead of saying that EUR/USD moved from 1.1000 to 1.1050, traders usually say the pair moved 50 pips. This makes it easier to discuss price movement across different forex pairs.' },
          { type: 'paragraph', text: 'The value of a pip depends on the currency pair, lot size, and account currency. This is why traders must understand position sizing before entering a trade.' },
          { type: 'heading', text: 'Pips in Risk Management' },
          { type: 'paragraph', text: 'Pips are also important for setting stop-loss and take-profit levels. A trader may risk 30 pips to target 60 pips, creating a risk-reward ratio of 1:2. This helps traders plan trades professionally instead of entering the market emotionally.' },
          { type: 'callout', text: '<strong>In simple words:</strong> A pip is a small unit used to measure price movement in forex. It helps traders calculate profit, loss, stop-loss, and target levels.' },
          { type: 'callout', text: '<strong>Disclaimer:</strong> This content is provided for general educational and informational purposes only. It does not constitute financial advice or a recommendation to buy, sell, or trade any currency or financial instrument. Pip value, profit, and loss may vary depending on the broker, account type, lot size, and leverage. The use of leverage can magnify both profits and losses. Conduct your own research and consult a qualified financial advisor before making any financial decision.' },
        ]
      },
      { id: 'what-is-spread', title: 'What is Spread in Forex?', level: 'Beginner', summary: 'How brokers make money and how spread affects your trades.',
        content: [
          { type: 'image', src: 'images/SNRFX005.jpg', alt: 'What is Spread in Forex' },
          { type: 'paragraph', text: 'Spread is the difference between the buying price and the selling price of a currency pair. In forex trading, every currency pair has two prices: the bid price and the ask price.' },
          { type: 'heading', text: 'Bid and Ask Price' },
          { type: 'paragraph', text: 'The bid price is the price at which a trader can sell a currency pair. The ask price is the price at which a trader can buy a currency pair. The difference between these two prices is called the spread.' },
          { type: 'paragraph', text: 'For example, if EUR/USD has a bid price of 1.1000 and an ask price of 1.1002, the spread is 2 pips. This means the trader enters the market with a small cost already included. The trade usually needs to move in the trader\'s favor by at least the spread amount before it reaches breakeven.' },
          { type: 'heading', text: 'Spread as a Trading Cost' },
          { type: 'paragraph', text: 'Spread is one of the main trading costs in forex. Lower spreads are generally better for traders, especially for short-term strategies such as scalping or intraday trading. Wider spreads can make trading more expensive and can reduce profitability.' },
          { type: 'heading', text: 'What Affects the Spread' },
          { type: 'paragraph', text: 'Spreads are affected by liquidity, volatility, market session, currency pair, broker pricing, and economic news. Major pairs such as EUR/USD usually have lower spreads because they are highly liquid. Exotic pairs often have wider spreads because they are less liquid and riskier.' },
          { type: 'paragraph', text: 'During major news events, spreads can widen quickly. This can cause unexpected entry prices, higher trading costs, or increased slippage. Professional traders always check the spread before placing a trade, especially during volatile market conditions.' },
          { type: 'callout', text: '<strong>In simple words:</strong> Spread is the difference between the buy price and sell price. It is one of the basic costs of forex trading.' },
          { type: 'callout', text: '<strong>Disclaimer:</strong> This content is provided for general educational and informational purposes only. It does not constitute financial advice or a recommendation to buy, sell, or trade any currency or financial instrument. Spreads may change due to market volatility, liquidity, and news events. Trading costs can affect profitability. The use of leverage can magnify both profits and losses. Conduct your own research and consult a qualified financial advisor before making any financial decision.' },
        ]
      },
      { id: 'lot-margin-leverage', title: 'Lot Size, Margin, and Leverage', level: 'Intermediate', summary: 'The three pillars of forex position sizing.',
        content: [
          { type: 'image', src: 'images/SNRFX006.jpg', alt: 'Lot Size Margin and Leverage' },
          { type: 'paragraph', text: 'Lot size, margin, and leverage are three important concepts in forex trading. These concepts directly affect trade size, risk exposure, profit potential, and possible loss.' },
          { type: 'heading', text: 'Lot Size' },
          { type: 'paragraph', text: 'A lot size represents the size of a forex trade. In general, forex trading uses standard lots, mini lots, micro lots, and sometimes nano lots depending on the broker. A standard lot usually represents 100,000 units of the base currency. A mini lot represents 10,000 units, and a micro lot represents 1,000 units. The larger the lot size, the greater the value of each pip movement.' },
          { type: 'heading', text: 'Margin' },
          { type: 'paragraph', text: 'Margin is the amount of money required to open and maintain a leveraged trade. It is not a fee, but a portion of account funds set aside by the broker as security for the position. If a trader opens a larger position, more margin is usually required.' },
          { type: 'heading', text: 'Leverage' },
          { type: 'paragraph', text: 'Leverage allows traders to control a larger position with a smaller amount of capital. For example, leverage of 1:100 means a trader can control a position much larger than the actual margin deposited. While leverage can increase profit potential, it also increases risk. A small market movement against the trade can result in a significant loss.' },
          { type: 'heading', text: 'Managing All Three Together' },
          { type: 'paragraph', text: 'Many beginner traders focus only on profit potential and ignore the danger of over-leverage. This is one of the most common mistakes in forex trading. Professional traders calculate position size carefully and decide risk before entering the market.' },
          { type: 'paragraph', text: 'Lot size, margin, and leverage should always be managed together. A trader must understand how much capital is at risk, how much margin is being used, and how much a pip movement can affect the account balance.' },
          { type: 'callout', text: '<strong>In simple words:</strong> Lot size controls trade volume, margin is the required security amount, and leverage allows traders to control larger positions with smaller capital. Together, they define the real risk of a forex trade.' },
          { type: 'callout', text: '<strong>Disclaimer:</strong> This content is provided for general educational and informational purposes only. It does not constitute financial advice or a recommendation to buy, sell, or trade any currency or financial instrument. Forex trading with margin and leverage involves a high level of risk. Leverage can magnify both profits and losses, and losses may occur quickly in volatile conditions. Conduct your own research and consult a qualified financial advisor before making any financial decision.' },
        ]
      },
      { id: 'fa-forex', title: 'Fundamental Analysis in Forex', level: 'Intermediate', summary: 'Using economic data and news to trade currencies.',
        content: [
          { type: 'image', src: 'images/SNRFX007.jpg', alt: 'Fundamental Analysis in Forex' },
          { type: 'paragraph', text: 'Fundamental analysis in forex focuses on understanding the economic, financial, and political factors that influence currency values. Unlike technical analysis, which studies price charts and patterns, fundamental analysis looks at the reasons behind currency movement.' },
          { type: 'heading', text: 'What Drives Currency Values' },
          { type: 'paragraph', text: 'Currencies are strongly affected by the economic strength of their countries. When an economy is growing, inflation is controlled, employment is strong, and interest rates are attractive, the currency may become stronger. When an economy is weak, inflation is unstable, or political uncertainty is high, the currency may lose value.' },
          { type: 'heading', text: 'Key Fundamental Factors' },
          { type: 'paragraph', text: 'Some of the most important factors in forex fundamental analysis include interest rates, inflation data, employment reports, gross domestic product, central bank policy, trade balance, consumer confidence, and geopolitical events. Central banks play a major role because their decisions on interest rates and monetary policy can create strong movements in currency markets.' },
          { type: 'paragraph', text: 'For example, if a central bank raises interest rates, its currency may strengthen because higher rates can attract investors looking for better returns. On the other hand, if a central bank signals rate cuts or economic weakness, the currency may weaken.' },
          { type: 'heading', text: 'How to Use Fundamental Analysis' },
          { type: 'paragraph', text: 'Fundamental analysis helps traders understand the bigger market picture. It can explain why a currency is trending strongly, why volatility is increasing, or why the market is reacting sharply to news. This approach is especially useful for swing traders, position traders, and investors who want to understand long-term currency direction.' },
          { type: 'paragraph', text: 'However, fundamental analysis is not always simple. Markets may react differently than expected because future expectations are often already priced in. Sometimes, good news may still cause a currency to fall if traders expected even better results.' },
          { type: 'heading', text: 'Combining with Technical Analysis' },
          { type: 'paragraph', text: 'Professional traders often combine fundamental analysis with technical analysis. Fundamentals help explain the reason behind market movement, while technical analysis helps identify entry points, exit points, and risk levels.' },
          { type: 'callout', text: '<strong>In simple words:</strong> Fundamental analysis in forex studies economic data, central bank decisions, and global events to understand why currencies move.' },
          { type: 'callout', text: '<strong>Disclaimer:</strong> This content is provided for general educational and informational purposes only. It does not constitute financial advice or a recommendation to buy, sell, or trade any currency or financial instrument. Forex markets can react unpredictably to economic data and global events. Fundamental analysis does not guarantee accurate predictions or profitable results. The use of leverage can magnify both profits and losses. Conduct your own research and consult a qualified financial advisor before making any financial decision.' },
        ]
      },
      { id: 'economic-calendar', title: 'Economic Calendar and News Trading', level: 'Intermediate', summary: 'How to use the economic calendar to anticipate market moves.',
        content: [
          { type: 'image', src: 'images/SNRFX008.jpg', alt: 'Economic Calendar and News Trading' },
          { type: 'paragraph', text: 'An economic calendar is an important tool used by forex traders to track upcoming financial events, economic data releases, and central bank announcements. These events can create strong movement in currency markets and may significantly affect trading conditions.' },
          { type: 'heading', text: 'What the Economic Calendar Includes' },
          { type: 'paragraph', text: 'The economic calendar usually includes events such as interest rate decisions, inflation reports, employment data, GDP announcements, retail sales, manufacturing data, consumer confidence reports, and central bank speeches. Each event normally shows the expected result, previous result, and actual result once released.' },
          { type: 'heading', text: 'News Trading' },
          { type: 'paragraph', text: 'News trading is a trading approach where traders make decisions based on economic news and market reaction. Some traders enter trades before the news based on expectations, while others wait for the news release and then trade the market reaction. Both approaches involve risk.' },
          { type: 'heading', text: 'Impact of High-Impact News' },
          { type: 'paragraph', text: 'High-impact news can cause rapid price movements, wider spreads, slippage, and increased volatility. For example, events such as US Non-Farm Payrolls, Federal Reserve interest rate decisions, inflation data, or major central bank speeches can move forex pairs sharply within seconds or minutes.' },
          { type: 'heading', text: 'Using the Calendar for Risk Management' },
          { type: 'paragraph', text: 'Professional traders use the economic calendar not only to find trading opportunities but also to manage risk. Even traders who do not trade news directly should be aware of upcoming high-impact events because open positions can be affected by sudden market movements.' },
          { type: 'paragraph', text: 'News trading requires discipline, speed, and strong risk control. It is not suitable for every trader, especially beginners. Market reaction can be unpredictable because price does not always move according to the data alone. Sometimes, the difference between actual results and market expectations matters more than the result itself.' },
          { type: 'callout', text: '<strong>In simple words:</strong> An economic calendar helps traders track important market events, while news trading involves making trading decisions based on economic announcements and market reactions.' },
          { type: 'callout', text: '<strong>Disclaimer:</strong> This content is provided for general educational and informational purposes only. It does not constitute financial advice or a recommendation to buy, sell, or trade any currency or financial instrument. News trading involves high risk. Market conditions may become extremely volatile, spreads may widen, and price may move unpredictably. Economic calendar data and forecasts do not guarantee any specific price movement. Conduct your own research and consult a qualified financial advisor before making any financial decision.' },
        ]
      },
    ]
  },

  // ── TECHNICAL ANALYSIS ─────────────────────────────────────────────────────
  {
    id: 'technical-analysis', icon: '📐', title: 'Technical Analysis',
    desc: 'Charts, candlesticks, indicators, price action, patterns, SMC, volume, and risk management.',
    topics: [
      { id: 'what-is-ta', title: 'What is Technical Analysis?', level: 'Beginner', summary: 'The foundation of chart-based trading and its core principles.',
        content: [
          { type: 'image', src: 'images/SNRTA001.jpg', alt: 'What is Technical Analysis' },
          { type: 'paragraph', text: 'Technical Analysis is a method used by traders and investors to study market price movement through charts, patterns, volume, and indicators. Instead of focusing only on company news or financial statements, technical analysis focuses on how price behaves on the chart.' },
          { type: 'paragraph', text: 'The main idea behind technical analysis is simple: price reflects market psychology. Every candle, trendline, support level, resistance zone, and volume movement shows how buyers and sellers are reacting in the market.' },
          { type: 'paragraph', text: 'Technical analysis can be used in different financial markets, including stocks, commodities, crypto, and forex.' },
          { type: 'heading', text: 'Why Technical Analysis is Important' },
          { type: 'paragraph', text: 'Technical analysis helps traders understand the current market direction and identify possible trading opportunities. It allows traders to study whether the market is moving upward, downward, or sideways.' },
          { type: 'paragraph', text: 'By using technical analysis, traders can make more structured decisions instead of entering trades based on emotions, rumors, or random guesses.' },
          { type: 'paragraph', text: 'It helps in:' },
          { type: 'list', items: [
            'Identifying market trends',
            'Finding support and resistance levels',
            'Understanding buyer and seller behavior',
            'Planning entry and exit points',
            'Managing risk through stop loss and target levels',
            'Studying price momentum using indicators',
          ]},
          { type: 'heading', text: 'Key Elements of Technical Analysis' },
          { type: 'heading', text: '1. Price Charts' },
          { type: 'paragraph', text: 'Price charts are the foundation of technical analysis. They show how the price of an asset has moved over time. Traders commonly use line charts, bar charts, and candlestick charts.' },
          { type: 'paragraph', text: 'Among these, candlestick charts are the most popular because they show the open, high, low, and close price in a clear visual format.' },
          { type: 'heading', text: '2. Candlestick Patterns' },
          { type: 'paragraph', text: 'Candlestick patterns help traders understand market sentiment. Some patterns show buying pressure, while others show selling pressure.' },
          { type: 'paragraph', text: 'For example, bullish candles may suggest strength in the market, while bearish candles may suggest weakness. Patterns like engulfing candles, doji, hammer, and shooting star are commonly used by traders.' },
          { type: 'heading', text: '3. Support and Resistance' },
          { type: 'paragraph', text: 'Support is a price level where buyers may enter the market and stop the price from falling further.' },
          { type: 'paragraph', text: 'Resistance is a price level where sellers may become active and stop the price from rising further.' },
          { type: 'paragraph', text: 'These levels are important because markets often react around them. Traders use support and resistance to plan entries, exits, stop losses, and profit targets.' },
          { type: 'heading', text: '4. Trendlines and Market Structure' },
          { type: 'paragraph', text: 'Trendlines help traders identify the direction of the market. If price is making higher highs and higher lows, the market is usually in an uptrend. If price is making lower highs and lower lows, the market is usually in a downtrend.' },
          { type: 'paragraph', text: 'Understanding market structure helps traders avoid trading against the main direction of the market.' },
          { type: 'heading', text: '5. Indicators and Volume' },
          { type: 'paragraph', text: 'Indicators are tools that help traders analyze price momentum, trend strength, and possible reversal points. Common indicators include RSI, MACD, Moving Averages, Bollinger Bands, and Volume.' },
          { type: 'paragraph', text: 'Volume is also very important because it shows the strength behind a price move. A breakout with high volume is usually more meaningful than a breakout with weak volume.' },
          { type: 'heading', text: 'Technical Analysis Does Not Predict with 100% Accuracy' },
          { type: 'paragraph', text: 'Technical analysis is not a magic formula and it does not guarantee profit. It only helps traders analyze probability.' },
          { type: 'paragraph', text: 'A professional trader does not use technical analysis to predict the future with certainty. Instead, the goal is to create a trading plan based on probability, confirmation, and risk management.' },
          { type: 'paragraph', text: 'Even the best technical setup can fail, which is why stop loss and position sizing are very important.' },
          { type: 'heading', text: 'Technical Analysis vs Fundamental Analysis' },
          { type: 'paragraph', text: 'Technical analysis studies price charts, trends, volume, and patterns.' },
          { type: 'paragraph', text: 'Fundamental analysis studies financial statements, company performance, earnings, economic data, interest rates, and business value.' },
          { type: 'paragraph', text: 'Both methods are useful. Many traders use technical analysis for timing entries and exits, while investors use fundamental analysis to understand the long-term value of an asset.' },
          { type: 'heading', text: 'Final Thoughts' },
          { type: 'paragraph', text: 'Technical analysis is one of the most important skills for anyone who wants to understand financial markets. It helps traders read charts, identify trends, understand market behavior, and manage risk properly.' },
          { type: 'paragraph', text: 'For beginners, the best approach is to start with the basics: candlesticks, support and resistance, trendlines, volume, and risk management. Once these foundations are clear, advanced tools like indicators, chart patterns, and smart money concepts become easier to understand.' },
          { type: 'paragraph', text: 'In simple words, technical analysis helps traders read the language of the market through price charts.' },
          { type: 'callout', text: '<strong>Disclaimer:</strong> This content is for educational purposes only and should not be considered financial advice. Trading and investing involve risk, and every learner should do proper research before making any financial decision.' },
        ]
      },
      { id: 'ta-vs-fa', title: 'Technical vs Fundamental Analysis', level: 'Beginner', summary: 'Comparing the two main schools of market analysis.',
        content: [
          { type: 'image', src: 'images/SNRTA002.jpg', alt: 'Technical vs Fundamental Analysis' },
          { type: 'paragraph', text: 'In trading and investing, two of the most widely used approaches for market analysis are Technical Analysis and Fundamental Analysis. Both methods help market participants make informed decisions, but they focus on different types of information.' },
          { type: 'heading', text: 'Technical Analysis' },
          { type: 'paragraph', text: 'Technical Analysis studies price action, chart patterns, volume, trends, support and resistance levels, indicators, and market behavior. It is based on the idea that price reflects all available information and that historical price movements can help identify possible future market direction. Traders often use technical analysis to find entry points, exit points, trend continuation signals, reversal areas, and risk management levels.' },
          { type: 'heading', text: 'Fundamental Analysis' },
          { type: 'paragraph', text: 'Fundamental Analysis focuses on the actual financial strength, business performance, economic environment, and intrinsic value of an asset. In stocks, this may include earnings, revenue growth, profit margins, debt levels, cash flow, management quality, industry outlook, and valuation ratios such as EPS, P/E ratio, book value, and dividend yield. Fundamental analysis is often used to determine whether an asset is undervalued, overvalued, or fairly priced.' },
          { type: 'heading', text: 'The Key Difference' },
          { type: 'paragraph', text: 'Technical Analysis focuses on price behavior, while Fundamental Analysis focuses on value and business quality. Technical analysts ask, "What is the price doing?" Fundamental analysts ask, "What is the asset really worth?"' },
          { type: 'heading', text: 'Which One to Use?' },
          { type: 'paragraph', text: 'For short-term trading, technical analysis is commonly used because it helps traders understand market timing, momentum, and price levels. For long-term investing, fundamental analysis is often preferred because it helps investors evaluate the financial health and future potential of a company or asset.' },
          { type: 'heading', text: 'Combining Both Approaches' },
          { type: 'paragraph', text: 'The strongest approach often comes from combining both methods. A trader or investor can use fundamental analysis to identify strong assets and technical analysis to decide the best time to enter or exit the market. For example, a fundamentally strong stock may still not be a good buy if the chart shows weak momentum or a major resistance zone. Similarly, a stock may look technically attractive, but poor fundamentals can increase risk.' },
          { type: 'paragraph', text: 'In professional trading, both approaches have value. Technical analysis improves timing and risk control, while fundamental analysis improves selection and long-term confidence. Understanding the difference between the two helps traders develop a more balanced, disciplined, and informed market strategy.' },
          { type: 'callout', text: '<strong>In simple words:</strong> Technical Analysis helps you understand <em>when</em> to trade, while Fundamental Analysis helps you understand <em>what</em> to trade. Together, they provide a more complete view of the market.' },
          { type: 'callout', text: '<strong>Disclaimer:</strong> The content provided in this educational library is for general information and learning purposes only. It should not be considered as financial advice, investment advice, trading advice, or a recommendation to buy, sell, or hold any financial instrument. Trading and investing involve significant risk, including the possible loss of capital. Past performance, chart patterns, or historical market behavior do not guarantee future results. Every trader or investor must conduct their own research, apply proper risk management, and make decisions based on their personal financial situation and risk tolerance. By reading or using this material, you acknowledge that you are fully responsible for your own trading and investment decisions.' },
        ]
      },
      { id: 'price-action', title: 'Understanding Price Action', level: 'Beginner', summary: 'Reading raw price movement without indicators.',
        content: [
          { type: 'image', src: 'images/SNRTA003.jpg', alt: 'Understanding Price Action' },
          { type: 'paragraph', text: 'Price Action is one of the most important concepts in technical analysis. It refers to the study of price movement on a chart without depending heavily on indicators. Instead of focusing only on external tools, price action helps traders understand how the market is behaving through candles, trends, support and resistance levels, market structure, and key price zones.' },
          { type: 'paragraph', text: 'In simple words, price action shows the real-time battle between buyers and sellers. When buyers are stronger, price usually moves upward. When sellers dominate, price moves downward. By reading price action correctly, traders can identify possible trend direction, reversal areas, breakout opportunities, and risk zones.' },
          { type: 'heading', text: 'How Price Action Works' },
          { type: 'paragraph', text: 'A price action trader observes how price reacts at important levels. These levels may include previous highs and lows, support and resistance zones, supply and demand areas, trendlines, and consolidation ranges. For example, if price reaches a strong support zone and forms a bullish candle pattern, it may indicate that buyers are entering the market. Similarly, if price reaches resistance and starts rejecting that level, sellers may be gaining control.' },
          { type: 'heading', text: 'The Role of Candlestick Behavior' },
          { type: 'paragraph', text: 'Candlestick behavior is also a major part of price action. Candle size, wick length, body strength, and closing position can provide valuable information about market sentiment. A strong bullish candle may show buying pressure, while a long upper wick near resistance may show selling pressure. These small details help traders understand whether the market is showing strength, weakness, hesitation, or rejection.' },
          { type: 'heading', text: 'Why Price Action is Widely Used' },
          { type: 'paragraph', text: 'Price action is widely used because it provides a clean and direct view of the market. Unlike indicators, which are often based on past price data, price action focuses on what price is doing right now. This makes it useful for traders who want to understand market movement in a practical and professional way.' },
          { type: 'heading', text: 'Important Caution' },
          { type: 'paragraph', text: 'Price action should not be used randomly. A trader must combine it with proper market structure, risk management, and confirmation. Not every candle pattern or breakout is reliable. False breakouts, fake moves, and emotional trading can lead to losses if price action is not analyzed carefully.' },
          { type: 'heading', text: 'Key Questions Price Action Answers' },
          { type: 'paragraph', text: 'Professional traders often use price action to answer key questions such as:' },
          { type: 'list', items: [
            'Where is the market trending?',
            'Where are buyers and sellers active?',
            'Is price rejecting or accepting a level?',
            'Is the market forming a breakout, reversal, or continuation?',
            'Where should risk be managed?',
          ]},
          { type: 'heading', text: 'Price Action as the Foundation' },
          { type: 'paragraph', text: 'The main strength of price action is that it helps traders understand the logic behind market movement. Instead of blindly following signals, traders learn to read the chart, observe market behavior, and make more disciplined decisions.' },
          { type: 'paragraph', text: 'Whether a trader uses indicators, Smart Money Concepts, support and resistance, or candlestick patterns, understanding price action improves market reading and decision-making.' },
          { type: 'callout', text: '<strong>In simple words:</strong> Price Action helps traders understand what the market is doing, where buyers and sellers are active, and how price is reacting at important levels.' },
          { type: 'callout', text: '<strong>Disclaimer:</strong> The content provided in this educational library is for general information and learning purposes only. It should not be considered financial advice, investment advice, trading advice, or a recommendation to buy, sell, or hold any financial instrument. Trading and investing involve significant risk, including the possible loss of capital. Past performance, chart patterns, indicators, strategies, or historical market behavior do not guarantee future results. Any examples, charts, or strategies shared are for educational explanation only and should not be treated as direct trading signals. Every trader or investor must conduct their own research, apply proper risk management, and make decisions based on their personal financial situation and risk tolerance. By reading or using this material, you acknowledge that you are fully responsible for your own trading and investment decisions.' },
        ]
      },
      { id: 'candlestick-charts',         title: 'Candlestick Charts Explained',                   level: 'Beginner',     summary: 'How to read and interpret candlestick charts.' },
      { id: 'candlestick-patterns',       title: 'Most Important Candlestick Patterns',            level: 'Beginner',     summary: 'The key candlestick formations every trader must know.' },
      { id: 'support-resistance',         title: 'Support and Resistance',                         level: 'Beginner',     summary: 'Identifying key price levels where the market reacts.' },
      { id: 'trendlines-channels',        title: 'Trendlines and Channels',                        level: 'Beginner',     summary: 'Drawing and trading dynamic support and resistance.' },
      { id: 'market-structure',           title: 'Market Structure: HH and LL',                   level: 'Beginner',     summary: 'Reading the sequence of highs and lows to define trend.' },
      { id: 'dow-theory',                 title: 'Dow Theory for Beginners',                       level: 'Beginner',     summary: 'The original framework for understanding market trends.' },
      { id: 'breakout-trading',           title: 'Breakout and Breakdown Trading',                 level: 'Intermediate', summary: 'Trading decisive moves beyond key levels.' },
      { id: 'fake-breakouts',             title: 'Fake Breakouts and Liquidity Traps',             level: 'Intermediate', summary: 'Identifying and avoiding false breakout setups.' },
      { id: 'volume-analysis',            title: 'Volume Analysis',                                level: 'Intermediate', summary: 'Using volume to confirm price moves and spot reversals.' },
      { id: 'moving-averages',            title: 'Moving Averages: SMA and EMA',                   level: 'Beginner',     summary: 'How moving averages smooth price and signal trend direction.' },
      { id: 'rsi-indicator',              title: 'RSI Indicator Explained',                        level: 'Beginner',     summary: 'Using RSI to spot overbought and oversold conditions.' },
      { id: 'macd-indicator',             title: 'MACD Indicator Explained',                       level: 'Intermediate', summary: 'The MACD indicator in practice — signal line, histogram, divergence.' },
      { id: 'bollinger-bands',            title: 'Bollinger Bands Explained',                      level: 'Intermediate', summary: 'Using Bollinger Bands to gauge volatility and price extremes.' },
      { id: 'fibonacci',                  title: 'Fibonacci Retracement and Extension',            level: 'Intermediate', summary: 'Using Fibonacci levels to find high-probability entries and targets.' },
      { id: 'chart-patterns-shapes',      title: 'Chart Patterns: Triangle, Flag, Wedge',         level: 'Intermediate', summary: 'Recognising and trading the most common continuation and reversal patterns.' },
      { id: 'head-and-shoulders',         title: 'Head and Shoulders Pattern',                     level: 'Intermediate', summary: 'The classic reversal pattern and how to trade it.' },
      { id: 'double-top-bottom',          title: 'Double Top and Double Bottom',                   level: 'Intermediate', summary: 'Identifying twin-peak and twin-valley reversal setups.' },
      { id: 'multi-timeframe',            title: 'Multi-Timeframe Analysis',                       level: 'Intermediate', summary: 'Using higher timeframes to confirm lower timeframe signals.' },
      { id: 'smc-intro',                  title: 'Smart Money Concepts Introduction',              level: 'Advanced',     summary: 'Understanding how institutional traders move markets.' },
      { id: 'ob-fvg-bos-choch',           title: 'Order Blocks, FVG, BOS and CHOCH',              level: 'Advanced',     summary: 'Key SMC concepts for identifying institutional footprints.' },
      { id: 'risk-reward',                title: 'Risk Reward Ratio in Trading',                   level: 'Beginner',     summary: 'Why your risk-to-reward ratio determines long-term profitability.' },
      { id: 'sl-tp-planning',             title: 'Stop Loss and Take Profit Planning',             level: 'Beginner',     summary: 'Placing logical stop losses and take profit levels on every trade.' },
    ]
  },

  // ── FUNDAMENTAL ANALYSIS ───────────────────────────────────────────────────
  {
    id: 'fundamental-analysis', icon: '📊', title: 'Fundamental Analysis',
    desc: 'Company valuation, financial statements, EPS, P/E ratio, macroeconomic data, and asset-based analysis.',
    topics: [
      { id: 'what-is-fa',                 title: 'What is Fundamental Analysis?',                  level: 'Beginner',     summary: 'The practice of evaluating an asset based on its intrinsic value.' },
      { id: 'why-fa-matters',             title: 'Why Fundamental Analysis Matters',               level: 'Beginner',     summary: 'How FA helps investors find undervalued opportunities.' },
      { id: 'company-financials',         title: 'Understanding Company Financial Statements',     level: 'Beginner',     summary: 'The three core financial documents every investor should read.' },
      { id: 'balance-sheet',              title: 'Balance Sheet Explained',                        level: 'Beginner',     summary: 'Assets, liabilities, and equity — reading a company\'s balance sheet.' },
      { id: 'income-statement',           title: 'Income Statement Explained',                     level: 'Beginner',     summary: 'Revenue, expenses, and profit on the income statement.' },
      { id: 'cash-flow-statement',        title: 'Cash Flow Statement Explained',                  level: 'Beginner',     summary: 'How cash moves in and out of a business.' },
      { id: 'revenue-profit-income',      title: 'Revenue, Profit, and Net Income',                level: 'Beginner',     summary: 'The difference between top-line and bottom-line numbers.' },
      { id: 'eps-explained',              title: 'EPS: Earnings Per Share Explained',              level: 'Beginner',     summary: 'What EPS reveals about a company\'s profitability per share.' },
      { id: 'pe-ratio-explained',         title: 'P/E Ratio Explained',                            level: 'Beginner',     summary: 'How to use the Price-to-Earnings ratio to value stocks.' },
      { id: 'book-value-pb',              title: 'Book Value and Price-to-Book Ratio',             level: 'Intermediate', summary: 'Measuring what a company is worth on paper vs its market price.' },
      { id: 'dividend-payout',            title: 'Dividend Yield and Payout Ratio',                level: 'Beginner',     summary: 'Evaluating how much a company returns to shareholders.' },
      { id: 'debt-to-equity',             title: 'Debt-to-Equity Ratio',                           level: 'Intermediate', summary: 'Measuring financial leverage and balance sheet risk.' },
      { id: 'roe-roa',                    title: 'Return on Equity and Return on Assets',          level: 'Intermediate', summary: 'Efficiency ratios that reveal how well a company uses its resources.' },
      { id: 'free-cash-flow',             title: 'Free Cash Flow Explained',                       level: 'Intermediate', summary: 'Why FCF is often more telling than reported profit.' },
      { id: 'market-cap-explained',       title: 'Market Capitalization Explained',                level: 'Beginner',     summary: 'Understanding the total market value of a company.' },
      { id: 'sector-industry',            title: 'Sector and Industry Analysis',                   level: 'Intermediate', summary: 'Evaluating companies within the context of their sector.' },
      { id: 'economic-moat',              title: 'Economic Moat and Competitive Advantage',        level: 'Intermediate', summary: 'What makes a business durable and hard to compete with.' },
      { id: 'growth-vs-value',            title: 'Growth Stocks vs Value Stocks',                  level: 'Intermediate', summary: 'Two contrasting investment philosophies explained.' },
      { id: 'undervalued-overvalued',     title: 'Undervalued vs Overvalued Stocks',               level: 'Intermediate', summary: 'How to determine if a stock is priced fairly.' },
      { id: 'interest-rates-markets',     title: 'Interest Rates and Their Impact on Markets',     level: 'Intermediate', summary: 'Why central bank decisions move stocks, bonds, and currencies.' },
      { id: 'inflation-investments',      title: 'Inflation and Its Impact on Investments',        level: 'Intermediate', summary: 'How rising prices erode or shift investment returns.' },
      { id: 'gdp-employment-sentiment',   title: 'GDP, Employment Data and Market Sentiment',      level: 'Intermediate', summary: 'Key macroeconomic indicators and how markets respond.' },
      { id: 'commodity-fa',               title: 'Commodity Fundamental Analysis',                 level: 'Intermediate', summary: 'Applying fundamental analysis to gold, oil, and other commodities.' },
      { id: 'crypto-fa',                  title: 'Crypto Fundamental Analysis',                    level: 'Intermediate', summary: 'Evaluating cryptocurrencies beyond price charts.' },
      { id: 'forex-fa',                   title: 'Forex Fundamental Analysis',                     level: 'Intermediate', summary: 'Using macroeconomic data to trade currency pairs.' },
    ]
  },
];
